### ISSUE TITLE
In installation instructions, say whether gem installs globally or per Ruby version

### ISSUE THREAD

**Issue by roryokane** [ryansouza/rbenv-rehash#2]
rbenv-rehash is an rbenv plugin, so I would expect that I would only have to install it once for my whole rbenv installation. But I know that `gem install` in an rbenv Ruby version generally installs that gem only for that Ruby version. So I’m not sure whether I have to run `gem install rbenv-rehash` just once total or once for each Ruby version I have installed, plus again if I every install a new Ruby version. So far I’ve been installing the `rbenv-rehash` for each Ruby version I have installed, just in case.

The [Installation section of the README](https://github.com/scoz/rbenv-rehash#installation) should say which installation requirement is the case. If you only have to install rbenv-rehash once, the information will save people time by stopping people uselessly installing it multiple times. If you have to install it for each Ruby version, the information will save people trouble by not having them wrongly expect a rehash to happen when they’re on a different Ruby version.

**Comment by scoz** [comment]
Thanks for pointing this out.

Its not actually a rbenv plugin, but a rubygems plugin, and will need to be installed on each separate ruby.

I've updated the readme :)
